package main

import (
	_ "path/to/project/utils/AbstractConnector"
	_ "path/to/project/utils/DeleteSet"
	_ "path/to/project/utils/Doc"
	_ "path/to/project/utils/UpdateDecoder"
	_ "path/to/project/utils/UpdateEncoder"
	_ "path/to/project/utils/encoding"
	_ "path/to/project/utils/EventHandler"
	_ "path/to/project/utils/ID"
	_ "path/to/project/utils/isParentOf"
	_ "path/to/project/utils/logging"
	_ "path/to/project/utils/PermanentUserData"
	_ "path/to/project/utils/RelativePosition"
	_ "path/to/project/utils/Snapshot"
	_ "path/to/project/utils/StructStore"
	_ "path/to/project/utils/Transaction"
	_ "path/to/project/utils/UndoManager"
	_ "path/to/project/utils/updates"
	_ "path/to/project/utils/YEvent"

	_ "path/to/project/types/AbstractType"
	_ "path/to/project/types/YArray"
	_ "path/to/project/types/YMap"
	_ "path/to/project/types/YText"
	_ "path/to/project/types/YXmlFragment"
	_ "path/to/project/types/YXmlElement"
	_ "path/to/project/types/YXmlEvent"
	_ "path/to/project/types/YXmlHook"
	_ "path/to/project/types/YXmlText"

	_ "path/to/project/structs/AbstractStruct"
	_ "path/to/project/structs/GC"
	_ "path/to/project/structs/ContentBinary"
	_ "path/to/project/structs/ContentDeleted"
	_ "path/to/project/structs/ContentDoc"
	_ "path/to/project/structs/ContentEmbed"
	_ "path/to/project/structs/ContentFormat"
	_ "path/to/project/structs/ContentJSON"
	_ "path/to/project/structs/ContentAny"
	_ "path/to/project/structs/ContentString"
	_ "path/to/project/structs/ContentType"
	_ "path/to/project/structs/Item"
	_ "path/to/project/structs/Skip"
)