# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.30'

RELEASE_GIT_HEAD = '505b400795af557bdcfd9d4fa7e9133b26ef431c'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2025.04.30'
