// Code generated by 'yaegi extract github.com/gosimple/slug'. DO NOT EDIT.

package symbol

import (
	"github.com/gosimple/slug"
	"reflect"
)

func init() {
	Symbols["github.com/gosimple/slug/slug"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AppendTimestamp":     reflect.ValueOf(&slug.AppendTimestamp).Elem(),
		"CustomRuneSub":       reflect.ValueOf(&slug.CustomRuneSub).Elem(),
		"CustomSub":           reflect.ValueOf(&slug.CustomSub).Elem(),
		"EnableSmartTruncate": reflect.ValueOf(&slug.EnableSmartTruncate).Elem(),
		"IsSlug":              reflect.ValueOf(slug.IsSlug),
		"Lowercase":           reflect.ValueOf(&slug.Lowercase).Elem(),
		"Make":                reflect.ValueOf(slug.Make),
		"MakeLang":            reflect.ValueOf(slug.MakeLang),
		"MaxLength":           reflect.ValueOf(&slug.MaxLength).Elem(),
		"Substitute":          reflect.ValueOf(slug.Substitute),
		"SubstituteRune":      reflect.ValueOf(slug.SubstituteRune),
	}
}
