// Code generated by 'yaegi extract github.com/breadchris/share/ai'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/ai"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/ai/ai"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":           reflect.ValueOf(ai.New),
		"WithContext":   reflect.ValueOf(ai.WithContext),
		"WithContextID": reflect.ValueOf(ai.WithContextID),

		// type definitions
		"AI": reflect.ValueOf((*ai.AI)(nil)),
	}
}
