// Code generated by 'yaegi extract github.com/russross/blackfriday/v2'. DO NOT EDIT.

package symbol

import (
	"github.com/russross/blackfriday/v2"
	"go/constant"
	"go/token"
	"io"
	"reflect"
)

func init() {
	Symbols["github.com/russross/blackfriday/v2/blackfriday"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AutoHeadingIDs":          reflect.ValueOf(blackfriday.AutoHeadingIDs),
		"Autolink":                reflect.ValueOf(blackfriday.Autolink),
		"BackslashLineBreak":      reflect.ValueOf(blackfriday.BackslashLineBreak),
		"BlockQuote":              reflect.ValueOf(blackfriday.BlockQuote),
		"Code":                    reflect.ValueOf(blackfriday.Code),
		"CodeBlock":               reflect.ValueOf(blackfriday.CodeBlock),
		"CommonExtensions":        reflect.ValueOf(blackfriday.CommonExtensions),
		"CommonHTMLFlags":         reflect.ValueOf(blackfriday.CommonHTMLFlags),
		"CompletePage":            reflect.ValueOf(blackfriday.CompletePage),
		"DefinitionLists":         reflect.ValueOf(blackfriday.DefinitionLists),
		"Del":                     reflect.ValueOf(blackfriday.Del),
		"Document":                reflect.ValueOf(blackfriday.Document),
		"Emph":                    reflect.ValueOf(blackfriday.Emph),
		"FencedCode":              reflect.ValueOf(blackfriday.FencedCode),
		"FootnoteReturnLinks":     reflect.ValueOf(blackfriday.FootnoteReturnLinks),
		"Footnotes":               reflect.ValueOf(blackfriday.Footnotes),
		"GoToNext":                reflect.ValueOf(blackfriday.GoToNext),
		"HTMLBlock":               reflect.ValueOf(blackfriday.HTMLBlock),
		"HTMLFlagsNone":           reflect.ValueOf(blackfriday.HTMLFlagsNone),
		"HTMLSpan":                reflect.ValueOf(blackfriday.HTMLSpan),
		"HardLineBreak":           reflect.ValueOf(blackfriday.HardLineBreak),
		"Hardbreak":               reflect.ValueOf(blackfriday.Hardbreak),
		"Heading":                 reflect.ValueOf(blackfriday.Heading),
		"HeadingIDs":              reflect.ValueOf(blackfriday.HeadingIDs),
		"HorizontalRule":          reflect.ValueOf(blackfriday.HorizontalRule),
		"HrefTargetBlank":         reflect.ValueOf(blackfriday.HrefTargetBlank),
		"Image":                   reflect.ValueOf(blackfriday.Image),
		"Item":                    reflect.ValueOf(blackfriday.Item),
		"LaxHTMLBlocks":           reflect.ValueOf(blackfriday.LaxHTMLBlocks),
		"Link":                    reflect.ValueOf(blackfriday.Link),
		"List":                    reflect.ValueOf(blackfriday.List),
		"ListItemBeginningOfList": reflect.ValueOf(blackfriday.ListItemBeginningOfList),
		"ListItemContainsBlock":   reflect.ValueOf(blackfriday.ListItemContainsBlock),
		"ListItemEndOfList":       reflect.ValueOf(blackfriday.ListItemEndOfList),
		"ListTypeDefinition":      reflect.ValueOf(blackfriday.ListTypeDefinition),
		"ListTypeOrdered":         reflect.ValueOf(blackfriday.ListTypeOrdered),
		"ListTypeTerm":            reflect.ValueOf(blackfriday.ListTypeTerm),
		"New":                     reflect.ValueOf(blackfriday.New),
		"NewHTMLRenderer":         reflect.ValueOf(blackfriday.NewHTMLRenderer),
		"NewNode":                 reflect.ValueOf(blackfriday.NewNode),
		"NewSmartypantsRenderer":  reflect.ValueOf(blackfriday.NewSmartypantsRenderer),
		"NoEmptyLineBeforeBlock":  reflect.ValueOf(blackfriday.NoEmptyLineBeforeBlock),
		"NoExtensions":            reflect.ValueOf(blackfriday.NoExtensions),
		"NoIntraEmphasis":         reflect.ValueOf(blackfriday.NoIntraEmphasis),
		"NofollowLinks":           reflect.ValueOf(blackfriday.NofollowLinks),
		"NoopenerLinks":           reflect.ValueOf(blackfriday.NoopenerLinks),
		"NoreferrerLinks":         reflect.ValueOf(blackfriday.NoreferrerLinks),
		"Paragraph":               reflect.ValueOf(blackfriday.Paragraph),
		"Run":                     reflect.ValueOf(blackfriday.Run),
		"Safelink":                reflect.ValueOf(blackfriday.Safelink),
		"SanitizedAnchorName":     reflect.ValueOf(blackfriday.SanitizedAnchorName),
		"SkipChildren":            reflect.ValueOf(blackfriday.SkipChildren),
		"SkipHTML":                reflect.ValueOf(blackfriday.SkipHTML),
		"SkipImages":              reflect.ValueOf(blackfriday.SkipImages),
		"SkipLinks":               reflect.ValueOf(blackfriday.SkipLinks),
		"Smartypants":             reflect.ValueOf(blackfriday.Smartypants),
		"SmartypantsAngledQuotes": reflect.ValueOf(blackfriday.SmartypantsAngledQuotes),
		"SmartypantsDashes":       reflect.ValueOf(blackfriday.SmartypantsDashes),
		"SmartypantsFractions":    reflect.ValueOf(blackfriday.SmartypantsFractions),
		"SmartypantsLatexDashes":  reflect.ValueOf(blackfriday.SmartypantsLatexDashes),
		"SmartypantsQuotesNBSP":   reflect.ValueOf(blackfriday.SmartypantsQuotesNBSP),
		"Softbreak":               reflect.ValueOf(blackfriday.Softbreak),
		"SpaceHeadings":           reflect.ValueOf(blackfriday.SpaceHeadings),
		"Strikethrough":           reflect.ValueOf(blackfriday.Strikethrough),
		"Strong":                  reflect.ValueOf(blackfriday.Strong),
		"TOC":                     reflect.ValueOf(blackfriday.TOC),
		"TabSizeDefault":          reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"TabSizeDouble":           reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"TabSizeEight":            reflect.ValueOf(blackfriday.TabSizeEight),
		"Table":                   reflect.ValueOf(blackfriday.Table),
		"TableAlignmentCenter":    reflect.ValueOf(blackfriday.TableAlignmentCenter),
		"TableAlignmentLeft":      reflect.ValueOf(blackfriday.TableAlignmentLeft),
		"TableAlignmentRight":     reflect.ValueOf(blackfriday.TableAlignmentRight),
		"TableBody":               reflect.ValueOf(blackfriday.TableBody),
		"TableCell":               reflect.ValueOf(blackfriday.TableCell),
		"TableHead":               reflect.ValueOf(blackfriday.TableHead),
		"TableRow":                reflect.ValueOf(blackfriday.TableRow),
		"Tables":                  reflect.ValueOf(blackfriday.Tables),
		"Terminate":               reflect.ValueOf(blackfriday.Terminate),
		"Text":                    reflect.ValueOf(blackfriday.Text),
		"Titleblock":              reflect.ValueOf(blackfriday.Titleblock),
		"UseXHTML":                reflect.ValueOf(blackfriday.UseXHTML),
		"Version":                 reflect.ValueOf(constant.MakeFromLiteral("\"2.0\"", token.STRING, 0)),
		"WithExtensions":          reflect.ValueOf(blackfriday.WithExtensions),
		"WithNoExtensions":        reflect.ValueOf(blackfriday.WithNoExtensions),
		"WithRefOverride":         reflect.ValueOf(blackfriday.WithRefOverride),
		"WithRenderer":            reflect.ValueOf(blackfriday.WithRenderer),

		// type definitions
		"CellAlignFlags":         reflect.ValueOf((*blackfriday.CellAlignFlags)(nil)),
		"CodeBlockData":          reflect.ValueOf((*blackfriday.CodeBlockData)(nil)),
		"Extensions":             reflect.ValueOf((*blackfriday.Extensions)(nil)),
		"HTMLFlags":              reflect.ValueOf((*blackfriday.HTMLFlags)(nil)),
		"HTMLRenderer":           reflect.ValueOf((*blackfriday.HTMLRenderer)(nil)),
		"HTMLRendererParameters": reflect.ValueOf((*blackfriday.HTMLRendererParameters)(nil)),
		"HeadingData":            reflect.ValueOf((*blackfriday.HeadingData)(nil)),
		"LinkData":               reflect.ValueOf((*blackfriday.LinkData)(nil)),
		"ListData":               reflect.ValueOf((*blackfriday.ListData)(nil)),
		"ListType":               reflect.ValueOf((*blackfriday.ListType)(nil)),
		"Markdown":               reflect.ValueOf((*blackfriday.Markdown)(nil)),
		"Node":                   reflect.ValueOf((*blackfriday.Node)(nil)),
		"NodeType":               reflect.ValueOf((*blackfriday.NodeType)(nil)),
		"NodeVisitor":            reflect.ValueOf((*blackfriday.NodeVisitor)(nil)),
		"Option":                 reflect.ValueOf((*blackfriday.Option)(nil)),
		"Reference":              reflect.ValueOf((*blackfriday.Reference)(nil)),
		"ReferenceOverrideFunc":  reflect.ValueOf((*blackfriday.ReferenceOverrideFunc)(nil)),
		"Renderer":               reflect.ValueOf((*blackfriday.Renderer)(nil)),
		"SPRenderer":             reflect.ValueOf((*blackfriday.SPRenderer)(nil)),
		"TableCellData":          reflect.ValueOf((*blackfriday.TableCellData)(nil)),
		"WalkStatus":             reflect.ValueOf((*blackfriday.WalkStatus)(nil)),

		// interface wrapper definitions
		"_Renderer": reflect.ValueOf((*_github_com_russross_blackfriday_v2_Renderer)(nil)),
	}
}

// _github_com_russross_blackfriday_v2_Renderer is an interface wrapper for Renderer type
type _github_com_russross_blackfriday_v2_Renderer struct {
	IValue        interface{}
	WRenderFooter func(w io.Writer, ast *blackfriday.Node)
	WRenderHeader func(w io.Writer, ast *blackfriday.Node)
	WRenderNode   func(w io.Writer, node *blackfriday.Node, entering bool) blackfriday.WalkStatus
}

func (W _github_com_russross_blackfriday_v2_Renderer) RenderFooter(w io.Writer, ast *blackfriday.Node) {
	W.WRenderFooter(w, ast)
}
func (W _github_com_russross_blackfriday_v2_Renderer) RenderHeader(w io.Writer, ast *blackfriday.Node) {
	W.WRenderHeader(w, ast)
}
func (W _github_com_russross_blackfriday_v2_Renderer) RenderNode(w io.Writer, node *blackfriday.Node, entering bool) blackfriday.WalkStatus {
	return W.WRenderNode(w, node, entering)
}
