// Code generated by 'yaegi extract github.com/breadchris/share/gen/proto/kanban'. DO NOT EDIT.

package symbol

import (
	"context"
	"github.com/breadchris/share/gen/proto/kanban"
	"google.golang.org/grpc"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/gen/proto/kanban/kanban"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"File_proto_kanban_kanban_proto": reflect.ValueOf(&kanban.File_proto_kanban_kanban_proto).Elem(),
		"KanbanService_ServiceDesc":      reflect.ValueOf(&kanban.KanbanService_ServiceDesc).Elem(),
		"NewKanbanServiceClient":         reflect.ValueOf(kanban.NewKanbanServiceClient),
		"RegisterKanbanServiceServer":    reflect.ValueOf(kanban.RegisterKanbanServiceServer),

		// type definitions
		"Board":                            reflect.ValueOf((*kanban.Board)(nil)),
		"Card":                             reflect.ValueOf((*kanban.Card)(nil)),
		"Column":                           reflect.ValueOf((*kanban.Column)(nil)),
		"CreateBoardRequest":               reflect.ValueOf((*kanban.CreateBoardRequest)(nil)),
		"CreateBoardResponse":              reflect.ValueOf((*kanban.CreateBoardResponse)(nil)),
		"CreateCardRequest":                reflect.ValueOf((*kanban.CreateCardRequest)(nil)),
		"CreateCardResponse":               reflect.ValueOf((*kanban.CreateCardResponse)(nil)),
		"CreateColumnRequest":              reflect.ValueOf((*kanban.CreateColumnRequest)(nil)),
		"CreateColumnResponse":             reflect.ValueOf((*kanban.CreateColumnResponse)(nil)),
		"DeleteBoardRequest":               reflect.ValueOf((*kanban.DeleteBoardRequest)(nil)),
		"DeleteBoardResponse":              reflect.ValueOf((*kanban.DeleteBoardResponse)(nil)),
		"DeleteCardRequest":                reflect.ValueOf((*kanban.DeleteCardRequest)(nil)),
		"DeleteCardResponse":               reflect.ValueOf((*kanban.DeleteCardResponse)(nil)),
		"DeleteColumnRequest":              reflect.ValueOf((*kanban.DeleteColumnRequest)(nil)),
		"DeleteColumnResponse":             reflect.ValueOf((*kanban.DeleteColumnResponse)(nil)),
		"GetBoardRequest":                  reflect.ValueOf((*kanban.GetBoardRequest)(nil)),
		"GetBoardResponse":                 reflect.ValueOf((*kanban.GetBoardResponse)(nil)),
		"KanbanServiceClient":              reflect.ValueOf((*kanban.KanbanServiceClient)(nil)),
		"KanbanServiceServer":              reflect.ValueOf((*kanban.KanbanServiceServer)(nil)),
		"ListBoardsRequest":                reflect.ValueOf((*kanban.ListBoardsRequest)(nil)),
		"ListBoardsResponse":               reflect.ValueOf((*kanban.ListBoardsResponse)(nil)),
		"MoveCardRequest":                  reflect.ValueOf((*kanban.MoveCardRequest)(nil)),
		"MoveCardResponse":                 reflect.ValueOf((*kanban.MoveCardResponse)(nil)),
		"MoveColumnRequest":                reflect.ValueOf((*kanban.MoveColumnRequest)(nil)),
		"MoveColumnResponse":               reflect.ValueOf((*kanban.MoveColumnResponse)(nil)),
		"UnimplementedKanbanServiceServer": reflect.ValueOf((*kanban.UnimplementedKanbanServiceServer)(nil)),
		"UnsafeKanbanServiceServer":        reflect.ValueOf((*kanban.UnsafeKanbanServiceServer)(nil)),
		"UpdateBoardRequest":               reflect.ValueOf((*kanban.UpdateBoardRequest)(nil)),
		"UpdateBoardResponse":              reflect.ValueOf((*kanban.UpdateBoardResponse)(nil)),
		"UpdateCardRequest":                reflect.ValueOf((*kanban.UpdateCardRequest)(nil)),
		"UpdateCardResponse":               reflect.ValueOf((*kanban.UpdateCardResponse)(nil)),
		"UpdateColumnRequest":              reflect.ValueOf((*kanban.UpdateColumnRequest)(nil)),
		"UpdateColumnResponse":             reflect.ValueOf((*kanban.UpdateColumnResponse)(nil)),

		// interface wrapper definitions
		"_KanbanServiceClient":       reflect.ValueOf((*_github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient)(nil)),
		"_KanbanServiceServer":       reflect.ValueOf((*_github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer)(nil)),
		"_UnsafeKanbanServiceServer": reflect.ValueOf((*_github_com_breadchris_share_gen_proto_kanban_UnsafeKanbanServiceServer)(nil)),
	}
}

// _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient is an interface wrapper for KanbanServiceClient type
type _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient struct {
	IValue        interface{}
	WCreateBoard  func(ctx context.Context, in *kanban.CreateBoardRequest, opts ...grpc.CallOption) (*kanban.CreateBoardResponse, error)
	WCreateCard   func(ctx context.Context, in *kanban.CreateCardRequest, opts ...grpc.CallOption) (*kanban.CreateCardResponse, error)
	WCreateColumn func(ctx context.Context, in *kanban.CreateColumnRequest, opts ...grpc.CallOption) (*kanban.CreateColumnResponse, error)
	WDeleteBoard  func(ctx context.Context, in *kanban.DeleteBoardRequest, opts ...grpc.CallOption) (*kanban.DeleteBoardResponse, error)
	WDeleteCard   func(ctx context.Context, in *kanban.DeleteCardRequest, opts ...grpc.CallOption) (*kanban.DeleteCardResponse, error)
	WDeleteColumn func(ctx context.Context, in *kanban.DeleteColumnRequest, opts ...grpc.CallOption) (*kanban.DeleteColumnResponse, error)
	WGetBoard     func(ctx context.Context, in *kanban.GetBoardRequest, opts ...grpc.CallOption) (*kanban.GetBoardResponse, error)
	WListBoards   func(ctx context.Context, in *kanban.ListBoardsRequest, opts ...grpc.CallOption) (*kanban.ListBoardsResponse, error)
	WMoveCard     func(ctx context.Context, in *kanban.MoveCardRequest, opts ...grpc.CallOption) (*kanban.MoveCardResponse, error)
	WMoveColumn   func(ctx context.Context, in *kanban.MoveColumnRequest, opts ...grpc.CallOption) (*kanban.MoveColumnResponse, error)
	WUpdateBoard  func(ctx context.Context, in *kanban.UpdateBoardRequest, opts ...grpc.CallOption) (*kanban.UpdateBoardResponse, error)
	WUpdateCard   func(ctx context.Context, in *kanban.UpdateCardRequest, opts ...grpc.CallOption) (*kanban.UpdateCardResponse, error)
	WUpdateColumn func(ctx context.Context, in *kanban.UpdateColumnRequest, opts ...grpc.CallOption) (*kanban.UpdateColumnResponse, error)
}

func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) CreateBoard(ctx context.Context, in *kanban.CreateBoardRequest, opts ...grpc.CallOption) (*kanban.CreateBoardResponse, error) {
	return W.WCreateBoard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) CreateCard(ctx context.Context, in *kanban.CreateCardRequest, opts ...grpc.CallOption) (*kanban.CreateCardResponse, error) {
	return W.WCreateCard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) CreateColumn(ctx context.Context, in *kanban.CreateColumnRequest, opts ...grpc.CallOption) (*kanban.CreateColumnResponse, error) {
	return W.WCreateColumn(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) DeleteBoard(ctx context.Context, in *kanban.DeleteBoardRequest, opts ...grpc.CallOption) (*kanban.DeleteBoardResponse, error) {
	return W.WDeleteBoard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) DeleteCard(ctx context.Context, in *kanban.DeleteCardRequest, opts ...grpc.CallOption) (*kanban.DeleteCardResponse, error) {
	return W.WDeleteCard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) DeleteColumn(ctx context.Context, in *kanban.DeleteColumnRequest, opts ...grpc.CallOption) (*kanban.DeleteColumnResponse, error) {
	return W.WDeleteColumn(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) GetBoard(ctx context.Context, in *kanban.GetBoardRequest, opts ...grpc.CallOption) (*kanban.GetBoardResponse, error) {
	return W.WGetBoard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) ListBoards(ctx context.Context, in *kanban.ListBoardsRequest, opts ...grpc.CallOption) (*kanban.ListBoardsResponse, error) {
	return W.WListBoards(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) MoveCard(ctx context.Context, in *kanban.MoveCardRequest, opts ...grpc.CallOption) (*kanban.MoveCardResponse, error) {
	return W.WMoveCard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) MoveColumn(ctx context.Context, in *kanban.MoveColumnRequest, opts ...grpc.CallOption) (*kanban.MoveColumnResponse, error) {
	return W.WMoveColumn(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) UpdateBoard(ctx context.Context, in *kanban.UpdateBoardRequest, opts ...grpc.CallOption) (*kanban.UpdateBoardResponse, error) {
	return W.WUpdateBoard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) UpdateCard(ctx context.Context, in *kanban.UpdateCardRequest, opts ...grpc.CallOption) (*kanban.UpdateCardResponse, error) {
	return W.WUpdateCard(ctx, in, opts...)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceClient) UpdateColumn(ctx context.Context, in *kanban.UpdateColumnRequest, opts ...grpc.CallOption) (*kanban.UpdateColumnResponse, error) {
	return W.WUpdateColumn(ctx, in, opts...)
}

// _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer is an interface wrapper for KanbanServiceServer type
type _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer struct {
	IValue        interface{}
	WCreateBoard  func(a0 context.Context, a1 *kanban.CreateBoardRequest) (*kanban.CreateBoardResponse, error)
	WCreateCard   func(a0 context.Context, a1 *kanban.CreateCardRequest) (*kanban.CreateCardResponse, error)
	WCreateColumn func(a0 context.Context, a1 *kanban.CreateColumnRequest) (*kanban.CreateColumnResponse, error)
	WDeleteBoard  func(a0 context.Context, a1 *kanban.DeleteBoardRequest) (*kanban.DeleteBoardResponse, error)
	WDeleteCard   func(a0 context.Context, a1 *kanban.DeleteCardRequest) (*kanban.DeleteCardResponse, error)
	WDeleteColumn func(a0 context.Context, a1 *kanban.DeleteColumnRequest) (*kanban.DeleteColumnResponse, error)
	WGetBoard     func(a0 context.Context, a1 *kanban.GetBoardRequest) (*kanban.GetBoardResponse, error)
	WListBoards   func(a0 context.Context, a1 *kanban.ListBoardsRequest) (*kanban.ListBoardsResponse, error)
	WMoveCard     func(a0 context.Context, a1 *kanban.MoveCardRequest) (*kanban.MoveCardResponse, error)
	WMoveColumn   func(a0 context.Context, a1 *kanban.MoveColumnRequest) (*kanban.MoveColumnResponse, error)
	WUpdateBoard  func(a0 context.Context, a1 *kanban.UpdateBoardRequest) (*kanban.UpdateBoardResponse, error)
	WUpdateCard   func(a0 context.Context, a1 *kanban.UpdateCardRequest) (*kanban.UpdateCardResponse, error)
	WUpdateColumn func(a0 context.Context, a1 *kanban.UpdateColumnRequest) (*kanban.UpdateColumnResponse, error)
}

func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) CreateBoard(a0 context.Context, a1 *kanban.CreateBoardRequest) (*kanban.CreateBoardResponse, error) {
	return W.WCreateBoard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) CreateCard(a0 context.Context, a1 *kanban.CreateCardRequest) (*kanban.CreateCardResponse, error) {
	return W.WCreateCard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) CreateColumn(a0 context.Context, a1 *kanban.CreateColumnRequest) (*kanban.CreateColumnResponse, error) {
	return W.WCreateColumn(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) DeleteBoard(a0 context.Context, a1 *kanban.DeleteBoardRequest) (*kanban.DeleteBoardResponse, error) {
	return W.WDeleteBoard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) DeleteCard(a0 context.Context, a1 *kanban.DeleteCardRequest) (*kanban.DeleteCardResponse, error) {
	return W.WDeleteCard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) DeleteColumn(a0 context.Context, a1 *kanban.DeleteColumnRequest) (*kanban.DeleteColumnResponse, error) {
	return W.WDeleteColumn(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) GetBoard(a0 context.Context, a1 *kanban.GetBoardRequest) (*kanban.GetBoardResponse, error) {
	return W.WGetBoard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) ListBoards(a0 context.Context, a1 *kanban.ListBoardsRequest) (*kanban.ListBoardsResponse, error) {
	return W.WListBoards(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) MoveCard(a0 context.Context, a1 *kanban.MoveCardRequest) (*kanban.MoveCardResponse, error) {
	return W.WMoveCard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) MoveColumn(a0 context.Context, a1 *kanban.MoveColumnRequest) (*kanban.MoveColumnResponse, error) {
	return W.WMoveColumn(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) UpdateBoard(a0 context.Context, a1 *kanban.UpdateBoardRequest) (*kanban.UpdateBoardResponse, error) {
	return W.WUpdateBoard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) UpdateCard(a0 context.Context, a1 *kanban.UpdateCardRequest) (*kanban.UpdateCardResponse, error) {
	return W.WUpdateCard(a0, a1)
}
func (W _github_com_breadchris_share_gen_proto_kanban_KanbanServiceServer) UpdateColumn(a0 context.Context, a1 *kanban.UpdateColumnRequest) (*kanban.UpdateColumnResponse, error) {
	return W.WUpdateColumn(a0, a1)
}

// _github_com_breadchris_share_gen_proto_kanban_UnsafeKanbanServiceServer is an interface wrapper for UnsafeKanbanServiceServer type
type _github_com_breadchris_share_gen_proto_kanban_UnsafeKanbanServiceServer struct {
	IValue interface{}
}
