// Code generated by 'yaegi extract github.com/breadchris/share/snapshot'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/snapshot"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/snapshot/snapshot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultComponentWatcherConfig": reflect.ValueOf(snapshot.DefaultComponentWatcherConfig),
		"DefaultViewports":              reflect.ValueOf(&snapshot.DefaultViewports).Elem(),

		// type definitions
		"ComponentWatcherConfig": reflect.ValueOf((*snapshot.ComponentWatcherConfig)(nil)),
		"Interaction":            reflect.ValueOf((*snapshot.Interaction)(nil)),
		"SnapshotConfig":         reflect.ValueOf((*snapshot.SnapshotConfig)(nil)),
		"SnapshotOptions":        reflect.ValueOf((*snapshot.SnapshotOptions)(nil)),
		"SnapshotResult":         reflect.ValueOf((*snapshot.SnapshotResult)(nil)),
		"Viewport":               reflect.ValueOf((*snapshot.Viewport)(nil)),
	}
}
