// Code generated by 'yaegi extract github.com/breadchris/share/calendar'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/graveyard/calendar"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/calendar/calendar"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DayMap":             reflect.ValueOf(calendar.DayMap),
		"DaysInMonth":        reflect.ValueOf(calendar.DaysInMonth),
		"EventMap":           reflect.ValueOf(calendar.EventMap),
		"InitializeCalendar": reflect.ValueOf(calendar.InitializeCalendar),
		"NewCalendar":        reflect.ValueOf(calendar.NewCalendar),
		"NewEventModal":      reflect.ValueOf(calendar.NewEventModal),
		"RenderCalendar":     reflect.ValueOf(calendar.RenderCalendar),
		"WeekMap":            reflect.ValueOf(calendar.WeekMap),

		// type definitions
		"Day":   reflect.ValueOf((*calendar.Day)(nil)),
		"Event": reflect.ValueOf((*calendar.Event)(nil)),
		"State": reflect.ValueOf((*calendar.State)(nil)),
	}
}
