// Code generated by 'yaegi extract github.com/go-shiori/go-readability'. DO NOT EDIT.

package symbol

import (
	"github.com/go-shiori/go-readability"
	"reflect"
)

func init() {
	Symbols["github.com/go-shiori/go-readability/readability"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Check":         reflect.ValueOf(readability.Check),
		"CheckDocument": reflect.ValueOf(readability.CheckDocument),
		"FromDocument":  reflect.ValueOf(readability.FromDocument),
		"FromReader":    reflect.ValueOf(readability.FromReader),
		"FromURL":       reflect.ValueOf(readability.FromURL),
		"NewParser":     reflect.ValueOf(readability.NewParser),

		// type definitions
		"Article": reflect.ValueOf((*readability.Article)(nil)),
		"Parser":  reflect.ValueOf((*readability.Parser)(nil)),
	}
}
