// Code generated by 'yaegi extract github.com/breadchris/share/session'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/session"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/session/session"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":            reflect.ValueOf(session.New),
		"NewFileStore":   reflect.ValueOf(session.NewFileStore),
		"UserIDCtxKey":   reflect.ValueOf(constant.MakeFromLiteral("\"user\"", token.STRING, 0)),
		"UserLoginError": reflect.ValueOf(&session.UserLoginError).Elem(),

		// type definitions
		"FileStore":      reflect.ValueOf((*session.FileStore)(nil)),
		"SessionManager": reflect.ValueOf((*session.SessionManager)(nil)),
	}
}
