// Code generated by 'yaegi extract github.com/breadchris/flow/config'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/flow/config"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/flow/config/config"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LoadConfig": reflect.ValueOf(config.LoadConfig),

		// type definitions
		"AppConfig":      reflect.ValueOf((*config.AppConfig)(nil)),
		"BlogConfig":     reflect.ValueOf((*config.BlogConfig)(nil)),
		"ClaudeConfig":   reflect.ValueOf((*config.ClaudeConfig)(nil)),
		"GitConfig":      reflect.ValueOf((*config.GitConfig)(nil)),
		"GithubConfig":   reflect.ValueOf((*config.GithubConfig)(nil)),
		"ProxyConfig":    reflect.ValueOf((*config.ProxyConfig)(nil)),
		"SMTPConfig":     reflect.ValueOf((*config.SMTPConfig)(nil)),
		"SlackBotConfig": reflect.ValueOf((*config.SlackBotConfig)(nil)),
		"SpotifyConfig":  reflect.ValueOf((*config.SpotifyConfig)(nil)),
		"Stripe":         reflect.ValueOf((*config.Stripe)(nil)),
		"WorkletConfig":  reflect.ValueOf((*config.WorkletConfig)(nil)),
	}
}
