// Code generated by 'yaegi extract github.com/breadchris/share/websocket'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/websocket"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/websocket/websocket"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewCommandRegistry": reflect.ValueOf(websocket.NewCommandRegistry),
		"NewWebsocketPage":   reflect.ValueOf(websocket.NewWebsocketPage),
		"SetupHandlers":      reflect.ValueOf(websocket.SetupHandlers),
		"WebsocketUI":        reflect.ValueOf(websocket.WebsocketUI),

		// type definitions
		"CommandFunc":        reflect.ValueOf((*websocket.CommandFunc)(nil)),
		"CommandFunc2":       reflect.ValueOf((*websocket.CommandFunc2)(nil)),
		"CommandRegistry":    reflect.ValueOf((*websocket.CommandRegistry)(nil)),
		"FieldDetail":        reflect.ValueOf((*websocket.FieldDetail)(nil)),
		"GenericCommandFunc": reflect.ValueOf((*websocket.GenericCommandFunc)(nil)),
		"Hub":                reflect.ValueOf((*websocket.Hub)(nil)),
		"WebsocketClient":    reflect.ValueOf((*websocket.WebsocketClient)(nil)),
	}
}
