// Code generated by 'yaegi extract github.com/snabb/sitemap'. DO NOT EDIT.

package symbol

import (
	"github.com/snabb/sitemap"
	"reflect"
)

func init() {
	Symbols["github.com/snabb/sitemap/sitemap"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Always":          reflect.ValueOf(sitemap.Always),
		"Daily":           reflect.ValueOf(sitemap.Daily),
		"Hourly":          reflect.ValueOf(sitemap.Hourly),
		"Monthly":         reflect.ValueOf(sitemap.Monthly),
		"Never":           reflect.ValueOf(sitemap.Never),
		"New":             reflect.ValueOf(sitemap.New),
		"NewSitemapIndex": reflect.ValueOf(sitemap.NewSitemapIndex),
		"Weekly":          reflect.ValueOf(sitemap.Weekly),
		"Yearly":          reflect.ValueOf(sitemap.Yearly),

		// type definitions
		"ChangeFreq":   reflect.ValueOf((*sitemap.ChangeFreq)(nil)),
		"Sitemap":      reflect.ValueOf((*sitemap.Sitemap)(nil)),
		"SitemapIndex": reflect.ValueOf((*sitemap.SitemapIndex)(nil)),
		"URL":          reflect.ValueOf((*sitemap.URL)(nil)),
	}
}
