// Code generated by 'yaegi extract github.com/stripe/stripe-go/v80/checkout/session'. DO NOT EDIT.

package symbol

import (
	"github.com/stripe/stripe-go/v80/checkout/session"
	"reflect"
)

func init() {
	Symbols["github.com/stripe/stripe-go/v80/checkout/session/session"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Expire":        reflect.ValueOf(session.Expire),
		"Get":           reflect.ValueOf(session.Get),
		"List":          reflect.ValueOf(session.List),
		"ListLineItems": reflect.ValueOf(session.ListLineItems),
		"New":           reflect.ValueOf(session.New),
		"Update":        reflect.ValueOf(session.Update),

		// type definitions
		"Client":       reflect.ValueOf((*session.Client)(nil)),
		"Iter":         reflect.ValueOf((*session.Iter)(nil)),
		"LineItemIter": reflect.ValueOf((*session.LineItemIter)(nil)),
	}
}
