// Code generated by 'yaegi extract github.com/breadchris/share/coderunner'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/coderunner"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/coderunner/coderunner"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LoadModule":              reflect.ValueOf(coderunner.LoadModule),
		"New":                     reflect.ValueOf(coderunner.New),
		"ServeReactApp":           reflect.ValueOf(coderunner.ServeReactApp),
		"ServeReactAppProduction": reflect.ValueOf(coderunner.ServeReactAppProduction),
		"ServeReactAppWithProps":  reflect.ValueOf(coderunner.ServeReactAppWithProps),

		// type definitions
		"BuildCache":      reflect.ValueOf((*coderunner.BuildCache)(nil)),
		"FileInfo":        reflect.ValueOf((*coderunner.FileInfo)(nil)),
		"SaveFileRequest": reflect.ValueOf((*coderunner.SaveFileRequest)(nil)),
	}
}
