// Code generated by 'yaegi extract github.com/breadchris/share/db'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/db"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/db/db"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LoadDB":                 reflect.ValueOf(db.LoadDB),
		"LoadSearchIndex":        reflect.ValueOf(db.LoadSearchIndex),
		"NewDBAny":               reflect.ValueOf(db.NewDBAny),
		"NewDocumentStore":       reflect.ValueOf(db.NewDocumentStore),
		"NewSearchIndex":         reflect.ValueOf(db.NewSearchIndex),
		"NewSqliteDocumentStore": reflect.ValueOf(db.NewSqliteDocumentStore),
		"WalkDirectory":          reflect.ValueOf(db.WalkDirectory),

		// type definitions
		"DBAny":           reflect.ValueOf((*db.DBAny)(nil)),
		"Document":        reflect.ValueOf((*db.Document)(nil)),
		"DocumentStore":   reflect.ValueOf((*db.DocumentStore)(nil)),
		"ProcessFileFunc": reflect.ValueOf((*db.ProcessFileFunc)(nil)),
		"SearchIndex":     reflect.ValueOf((*db.SearchIndex)(nil)),
	}
}
