// Code generated by 'yaegi extract github.com/traefik/yaegi/stdlib'. DO NOT EDIT.

package symbol

import (
	"github.com/traefik/yaegi/stdlib"
	"reflect"
)

func init() {
	Symbols["github.com/traefik/yaegi/stdlib/stdlib"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"MapTypes": reflect.ValueOf(&stdlib.MapTypes).Elem(),
		"Symbols":  reflect.ValueOf(&stdlib.Symbols).Elem(),
	}
}
