// Code generated by 'yaegi extract github.com/breadchris/share/config'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/config"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/config/config"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(config.New),

		// type definitions
		"AppConfig":     reflect.ValueOf((*config.AppConfig)(nil)),
		"SMTPConfig":    reflect.ValueOf((*config.SMTPConfig)(nil)),
		"SpotifyConfig": reflect.ValueOf((*config.SpotifyConfig)(nil)),
	}
}
