// Code generated by 'yaegi extract github.com/breadchris/share/llm'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/graveyard/llm"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/llm/llm"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ChatGPTMsg":       reflect.ValueOf(llm.ChatGPTMsg),
		"NewChatGPT":       reflect.ValueOf(llm.NewChatGPT),
		"NewOpenAIService": reflect.ValueOf(llm.NewOpenAIService),
		"Upgrader":         reflect.ValueOf(&llm.Upgrader).Elem(),

		// type definitions
		"ChatMessage":   reflect.ValueOf((*llm.ChatMessage)(nil)),
		"ChatState":     reflect.ValueOf((*llm.ChatState)(nil)),
		"InferRequest":  reflect.ValueOf((*llm.InferRequest)(nil)),
		"OpenAIService": reflect.ValueOf((*llm.OpenAIService)(nil)),
	}
}
