// Code generated by 'yaegi extract github.com/breadchris/share/models'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/models"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/models/models"] = map[string]reflect.Value{
		// type definitions
		"Group":           reflect.ValueOf((*models.Group)(nil)),
		"GroupMembership": reflect.ValueOf((*models.GroupMembership)(nil)),
		"Identity":        reflect.ValueOf((*models.Identity)(nil)),
		"User":            reflect.ValueOf((*models.User)(nil)),
	}
}
