// Code generated by 'yaegi extract github.com/dsoprea/go-exif/v2/common'. DO NOT EDIT.

package symbol

import (
	"github.com/dsoprea/go-exif/v2/common"
	"reflect"
)

func init() {
	Symbols["github.com/dsoprea/go-exif/v2/common/exifcommon"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DumpBytes":                     reflect.ValueOf(exifcommon.DumpBytes),
		"DumpBytesClause":               reflect.ValueOf(exifcommon.DumpBytesClause),
		"DumpBytesClauseToString":       reflect.ValueOf(exifcommon.DumpBytesClauseToString),
		"DumpBytesToString":             reflect.ValueOf(exifcommon.DumpBytesToString),
		"EncodeDefaultByteOrder":        reflect.ValueOf(&exifcommon.EncodeDefaultByteOrder).Elem(),
		"ErrChildIfdNotMapped":          reflect.ValueOf(&exifcommon.ErrChildIfdNotMapped).Elem(),
		"ErrNotEnoughData":              reflect.ValueOf(&exifcommon.ErrNotEnoughData).Elem(),
		"ErrNotFarValue":                reflect.ValueOf(&exifcommon.ErrNotFarValue).Elem(),
		"ErrUnhandledUndefinedTypedTag": reflect.ValueOf(&exifcommon.ErrUnhandledUndefinedTypedTag).Elem(),
		"ErrWrongType":                  reflect.ValueOf(&exifcommon.ErrWrongType).Elem(),
		"ExifFullTimestampString":       reflect.ValueOf(exifcommon.ExifFullTimestampString),
		"FormatFromBytes":               reflect.ValueOf(exifcommon.FormatFromBytes),
		"FormatFromType":                reflect.ValueOf(exifcommon.FormatFromType),
		"GetModuleRootPath":             reflect.ValueOf(exifcommon.GetModuleRootPath),
		"GetTestAssetsPath":             reflect.ValueOf(exifcommon.GetTestAssetsPath),
		"GetTypeByName":                 reflect.ValueOf(exifcommon.GetTypeByName),
		"Ifd1StandardIfdIdentity":       reflect.ValueOf(&exifcommon.Ifd1StandardIfdIdentity).Elem(),
		"IfdExifIopStandardIfdIdentity": reflect.ValueOf(&exifcommon.IfdExifIopStandardIfdIdentity).Elem(),
		"IfdExifStandardIfdIdentity":    reflect.ValueOf(&exifcommon.IfdExifStandardIfdIdentity).Elem(),
		"IfdGpsInfoStandardIfdIdentity": reflect.ValueOf(&exifcommon.IfdGpsInfoStandardIfdIdentity).Elem(),
		"IfdPathStandard":               reflect.ValueOf(&exifcommon.IfdPathStandard).Elem(),
		"IfdPathStandardExif":           reflect.ValueOf(&exifcommon.IfdPathStandardExif).Elem(),
		"IfdPathStandardExifIop":        reflect.ValueOf(&exifcommon.IfdPathStandardExifIop).Elem(),
		"IfdPathStandardGps":            reflect.ValueOf(&exifcommon.IfdPathStandardGps).Elem(),
		"IfdStandardIfdIdentity":        reflect.ValueOf(&exifcommon.IfdStandardIfdIdentity).Elem(),
		"LoadStandardIfds":              reflect.ValueOf(exifcommon.LoadStandardIfds),
		"NewIfdIdentity":                reflect.ValueOf(exifcommon.NewIfdIdentity),
		"NewIfdIdentityFromString":      reflect.ValueOf(exifcommon.NewIfdIdentityFromString),
		"NewIfdMapping":                 reflect.ValueOf(exifcommon.NewIfdMapping),
		"NewIfdMappingWithStandard":     reflect.ValueOf(exifcommon.NewIfdMappingWithStandard),
		"NewIfdTag":                     reflect.ValueOf(exifcommon.NewIfdTag),
		"NewValueContext":               reflect.ValueOf(exifcommon.NewValueContext),
		"NewValueEncoder":               reflect.ValueOf(exifcommon.NewValueEncoder),
		"TestDefaultByteOrder":          reflect.ValueOf(&exifcommon.TestDefaultByteOrder).Elem(),
		"TranslateStringToType":         reflect.ValueOf(exifcommon.TranslateStringToType),
		"TypeAscii":                     reflect.ValueOf(exifcommon.TypeAscii),
		"TypeAsciiNoNul":                reflect.ValueOf(exifcommon.TypeAsciiNoNul),
		"TypeByte":                      reflect.ValueOf(exifcommon.TypeByte),
		"TypeLong":                      reflect.ValueOf(exifcommon.TypeLong),
		"TypeNames":                     reflect.ValueOf(&exifcommon.TypeNames).Elem(),
		"TypeRational":                  reflect.ValueOf(exifcommon.TypeRational),
		"TypeShort":                     reflect.ValueOf(exifcommon.TypeShort),
		"TypeSignedLong":                reflect.ValueOf(exifcommon.TypeSignedLong),
		"TypeSignedRational":            reflect.ValueOf(exifcommon.TypeSignedRational),
		"TypeUndefined":                 reflect.ValueOf(exifcommon.TypeUndefined),

		// type definitions
		"BasicTag":         reflect.ValueOf((*exifcommon.BasicTag)(nil)),
		"EncodedData":      reflect.ValueOf((*exifcommon.EncodedData)(nil)),
		"IfdIdentity":      reflect.ValueOf((*exifcommon.IfdIdentity)(nil)),
		"IfdIdentityPart":  reflect.ValueOf((*exifcommon.IfdIdentityPart)(nil)),
		"IfdMapping":       reflect.ValueOf((*exifcommon.IfdMapping)(nil)),
		"IfdTag":           reflect.ValueOf((*exifcommon.IfdTag)(nil)),
		"IfdTagIdAndIndex": reflect.ValueOf((*exifcommon.IfdTagIdAndIndex)(nil)),
		"MappedIfd":        reflect.ValueOf((*exifcommon.MappedIfd)(nil)),
		"Parser":           reflect.ValueOf((*exifcommon.Parser)(nil)),
		"Rational":         reflect.ValueOf((*exifcommon.Rational)(nil)),
		"SignedRational":   reflect.ValueOf((*exifcommon.SignedRational)(nil)),
		"TagTypePrimitive": reflect.ValueOf((*exifcommon.TagTypePrimitive)(nil)),
		"ValueContext":     reflect.ValueOf((*exifcommon.ValueContext)(nil)),
		"ValueEncoder":     reflect.ValueOf((*exifcommon.ValueEncoder)(nil)),
	}
}
