// Code generated by 'yaegi extract github.com/breadchris/share/coderunner/claude'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/coderunner/claude"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/coderunner/claude/claude"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewClaudeService": reflect.ValueOf(claude.NewClaudeService),

		// type definitions
		"ClaudeInitMessage": reflect.ValueOf((*claude.ClaudeInitMessage)(nil)),
		"ClaudeMessage":     reflect.ValueOf((*claude.ClaudeMessage)(nil)),
		"ClaudeProcess":     reflect.ValueOf((*claude.ClaudeProcess)(nil)),
		"ClaudePrompt":      reflect.ValueOf((*claude.ClaudePrompt)(nil)),
		"ClaudeService":     reflect.ValueOf((*claude.ClaudeService)(nil)),
		"WSMessage":         reflect.ValueOf((*claude.WSMessage)(nil)),
	}
}
