// Code generated by 'yaegi extract github.com/traefik/yaegi'. DO NOT EDIT.

package symbol

import (
	"reflect"
)

func init() {
	Symbols["github.com/traefik/yaegi/yaegi"] = map[string]reflect.Value{}
}
