// Code generated by 'yaegi extract github.com/breadchris/share/breadchris/posts'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/breadchris/posts"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/breadchris/posts/posts"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ExtractText": reflect.ValueOf(posts.ExtractText),
		"LoadPosts":   reflect.ValueOf(posts.LoadPosts),

		// type definitions
		"Post": reflect.ValueOf((*posts.Post)(nil)),
	}
}
