// Code generated by 'yaegi extract github.com/dsoprea/go-jpeg-image-structure/v2'. DO NOT EDIT.

package symbol

import (
	"github.com/dsoprea/go-jpeg-image-structure/v2"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/dsoprea/go-jpeg-image-structure/v2/jpegstructure"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DumpBytes":               reflect.ValueOf(jpegstructure.DumpBytes),
		"DumpBytesClause":         reflect.ValueOf(jpegstructure.DumpBytesClause),
		"DumpBytesClauseToString": reflect.ValueOf(jpegstructure.DumpBytesClauseToString),
		"DumpBytesToString":       reflect.ValueOf(jpegstructure.DumpBytesToString),
		"ErrNoIptc":               reflect.ValueOf(&jpegstructure.ErrNoIptc).Elem(),
		"ErrNoPhotoshopData":      reflect.ValueOf(&jpegstructure.ErrNoPhotoshopData).Elem(),
		"ErrNoXmp":                reflect.ValueOf(&jpegstructure.ErrNoXmp).Elem(),
		"FormatXml":               reflect.ValueOf(jpegstructure.FormatXml),
		"GetModuleRootPath":       reflect.ValueOf(jpegstructure.GetModuleRootPath),
		"GetTestAssetsPath":       reflect.ValueOf(jpegstructure.GetTestAssetsPath),
		"GetTestImageFilepath":    reflect.ValueOf(jpegstructure.GetTestImageFilepath),
		"MARKER_APP0":             reflect.ValueOf(constant.MakeFromLiteral("224", token.INT, 0)),
		"MARKER_APP1":             reflect.ValueOf(constant.MakeFromLiteral("225", token.INT, 0)),
		"MARKER_APP10":            reflect.ValueOf(constant.MakeFromLiteral("234", token.INT, 0)),
		"MARKER_APP12":            reflect.ValueOf(constant.MakeFromLiteral("236", token.INT, 0)),
		"MARKER_APP13":            reflect.ValueOf(constant.MakeFromLiteral("237", token.INT, 0)),
		"MARKER_APP14":            reflect.ValueOf(constant.MakeFromLiteral("238", token.INT, 0)),
		"MARKER_APP15":            reflect.ValueOf(constant.MakeFromLiteral("239", token.INT, 0)),
		"MARKER_APP2":             reflect.ValueOf(constant.MakeFromLiteral("226", token.INT, 0)),
		"MARKER_APP3":             reflect.ValueOf(constant.MakeFromLiteral("227", token.INT, 0)),
		"MARKER_APP4":             reflect.ValueOf(constant.MakeFromLiteral("228", token.INT, 0)),
		"MARKER_APP5":             reflect.ValueOf(constant.MakeFromLiteral("229", token.INT, 0)),
		"MARKER_APP6":             reflect.ValueOf(constant.MakeFromLiteral("230", token.INT, 0)),
		"MARKER_APP7":             reflect.ValueOf(constant.MakeFromLiteral("231", token.INT, 0)),
		"MARKER_APP8":             reflect.ValueOf(constant.MakeFromLiteral("232", token.INT, 0)),
		"MARKER_CME":              reflect.ValueOf(constant.MakeFromLiteral("100", token.INT, 0)),
		"MARKER_COM":              reflect.ValueOf(constant.MakeFromLiteral("254", token.INT, 0)),
		"MARKER_DAC":              reflect.ValueOf(constant.MakeFromLiteral("204", token.INT, 0)),
		"MARKER_DHT":              reflect.ValueOf(constant.MakeFromLiteral("196", token.INT, 0)),
		"MARKER_DQT":              reflect.ValueOf(constant.MakeFromLiteral("219", token.INT, 0)),
		"MARKER_EOI":              reflect.ValueOf(constant.MakeFromLiteral("217", token.INT, 0)),
		"MARKER_JPG":              reflect.ValueOf(constant.MakeFromLiteral("200", token.INT, 0)),
		"MARKER_SIZ":              reflect.ValueOf(constant.MakeFromLiteral("81", token.INT, 0)),
		"MARKER_SOD":              reflect.ValueOf(constant.MakeFromLiteral("147", token.INT, 0)),
		"MARKER_SOF0":             reflect.ValueOf(constant.MakeFromLiteral("192", token.INT, 0)),
		"MARKER_SOF1":             reflect.ValueOf(constant.MakeFromLiteral("193", token.INT, 0)),
		"MARKER_SOF10":            reflect.ValueOf(constant.MakeFromLiteral("202", token.INT, 0)),
		"MARKER_SOF11":            reflect.ValueOf(constant.MakeFromLiteral("203", token.INT, 0)),
		"MARKER_SOF13":            reflect.ValueOf(constant.MakeFromLiteral("205", token.INT, 0)),
		"MARKER_SOF14":            reflect.ValueOf(constant.MakeFromLiteral("206", token.INT, 0)),
		"MARKER_SOF15":            reflect.ValueOf(constant.MakeFromLiteral("207", token.INT, 0)),
		"MARKER_SOF2":             reflect.ValueOf(constant.MakeFromLiteral("194", token.INT, 0)),
		"MARKER_SOF3":             reflect.ValueOf(constant.MakeFromLiteral("195", token.INT, 0)),
		"MARKER_SOF5":             reflect.ValueOf(constant.MakeFromLiteral("197", token.INT, 0)),
		"MARKER_SOF6":             reflect.ValueOf(constant.MakeFromLiteral("198", token.INT, 0)),
		"MARKER_SOF7":             reflect.ValueOf(constant.MakeFromLiteral("199", token.INT, 0)),
		"MARKER_SOF9":             reflect.ValueOf(constant.MakeFromLiteral("201", token.INT, 0)),
		"MARKER_SOI":              reflect.ValueOf(constant.MakeFromLiteral("216", token.INT, 0)),
		"MARKER_SOS":              reflect.ValueOf(constant.MakeFromLiteral("218", token.INT, 0)),
		"NewJpegMediaParser":      reflect.ValueOf(jpegstructure.NewJpegMediaParser),
		"NewJpegSplitter":         reflect.ValueOf(jpegstructure.NewJpegSplitter),
		"NewSegmentList":          reflect.ValueOf(jpegstructure.NewSegmentList),
		"SortStringStringMap":     reflect.ValueOf(jpegstructure.SortStringStringMap),

		// type definitions
		"JpegMediaParser":   reflect.ValueOf((*jpegstructure.JpegMediaParser)(nil)),
		"JpegSplitter":      reflect.ValueOf((*jpegstructure.JpegSplitter)(nil)),
		"Segment":           reflect.ValueOf((*jpegstructure.Segment)(nil)),
		"SegmentList":       reflect.ValueOf((*jpegstructure.SegmentList)(nil)),
		"SegmentVisitor":    reflect.ValueOf((*jpegstructure.SegmentVisitor)(nil)),
		"SofSegment":        reflect.ValueOf((*jpegstructure.SofSegment)(nil)),
		"SofSegmentVisitor": reflect.ValueOf((*jpegstructure.SofSegmentVisitor)(nil)),

		// interface wrapper definitions
		"_SegmentVisitor":    reflect.ValueOf((*_github_com_dsoprea_go_jpeg_image_structure_v2_SegmentVisitor)(nil)),
		"_SofSegmentVisitor": reflect.ValueOf((*_github_com_dsoprea_go_jpeg_image_structure_v2_SofSegmentVisitor)(nil)),
	}
}

// _github_com_dsoprea_go_jpeg_image_structure_v2_SegmentVisitor is an interface wrapper for SegmentVisitor type
type _github_com_dsoprea_go_jpeg_image_structure_v2_SegmentVisitor struct {
	IValue         interface{}
	WHandleSegment func(markerId byte, markerName string, counter int, lastIsScanData bool) error
}

func (W _github_com_dsoprea_go_jpeg_image_structure_v2_SegmentVisitor) HandleSegment(markerId byte, markerName string, counter int, lastIsScanData bool) error {
	return W.WHandleSegment(markerId, markerName, counter, lastIsScanData)
}

// _github_com_dsoprea_go_jpeg_image_structure_v2_SofSegmentVisitor is an interface wrapper for SofSegmentVisitor type
type _github_com_dsoprea_go_jpeg_image_structure_v2_SofSegmentVisitor struct {
	IValue     interface{}
	WHandleSof func(sof *jpegstructure.SofSegment) error
}

func (W _github_com_dsoprea_go_jpeg_image_structure_v2_SofSegmentVisitor) HandleSof(sof *jpegstructure.SofSegment) error {
	return W.WHandleSof(sof)
}
