// Code generated by 'yaegi extract github.com/breadchris/share/gen/proto/kanban'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/gen/proto/kanban"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/gen/proto/kanban/kanban"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"File_proto_kanban_kanban_proto": reflect.ValueOf(&kanban.File_proto_kanban_kanban_proto).Elem(),

		// type definitions
		"Board":                reflect.ValueOf((*kanban.Board)(nil)),
		"Card":                 reflect.ValueOf((*kanban.Card)(nil)),
		"Column":               reflect.ValueOf((*kanban.Column)(nil)),
		"CreateBoardRequest":   reflect.ValueOf((*kanban.CreateBoardRequest)(nil)),
		"CreateBoardResponse":  reflect.ValueOf((*kanban.CreateBoardResponse)(nil)),
		"CreateCardRequest":    reflect.ValueOf((*kanban.CreateCardRequest)(nil)),
		"CreateCardResponse":   reflect.ValueOf((*kanban.CreateCardResponse)(nil)),
		"CreateColumnRequest":  reflect.ValueOf((*kanban.CreateColumnRequest)(nil)),
		"CreateColumnResponse": reflect.ValueOf((*kanban.CreateColumnResponse)(nil)),
		"DeleteBoardRequest":   reflect.ValueOf((*kanban.DeleteBoardRequest)(nil)),
		"DeleteBoardResponse":  reflect.ValueOf((*kanban.DeleteBoardResponse)(nil)),
		"DeleteCardRequest":    reflect.ValueOf((*kanban.DeleteCardRequest)(nil)),
		"DeleteCardResponse":   reflect.ValueOf((*kanban.DeleteCardResponse)(nil)),
		"DeleteColumnRequest":  reflect.ValueOf((*kanban.DeleteColumnRequest)(nil)),
		"DeleteColumnResponse": reflect.ValueOf((*kanban.DeleteColumnResponse)(nil)),
		"GetBoardRequest":      reflect.ValueOf((*kanban.GetBoardRequest)(nil)),
		"GetBoardResponse":     reflect.ValueOf((*kanban.GetBoardResponse)(nil)),
		"ListBoardsRequest":    reflect.ValueOf((*kanban.ListBoardsRequest)(nil)),
		"ListBoardsResponse":   reflect.ValueOf((*kanban.ListBoardsResponse)(nil)),
		"MoveCardRequest":      reflect.ValueOf((*kanban.MoveCardRequest)(nil)),
		"MoveCardResponse":     reflect.ValueOf((*kanban.MoveCardResponse)(nil)),
		"MoveColumnRequest":    reflect.ValueOf((*kanban.MoveColumnRequest)(nil)),
		"MoveColumnResponse":   reflect.ValueOf((*kanban.MoveColumnResponse)(nil)),
		"UpdateBoardRequest":   reflect.ValueOf((*kanban.UpdateBoardRequest)(nil)),
		"UpdateBoardResponse":  reflect.ValueOf((*kanban.UpdateBoardResponse)(nil)),
		"UpdateCardRequest":    reflect.ValueOf((*kanban.UpdateCardRequest)(nil)),
		"UpdateCardResponse":   reflect.ValueOf((*kanban.UpdateCardResponse)(nil)),
		"UpdateColumnRequest":  reflect.ValueOf((*kanban.UpdateColumnRequest)(nil)),
		"UpdateColumnResponse": reflect.ValueOf((*kanban.UpdateColumnResponse)(nil)),
	}
}
