// Code generated by 'yaegi extract github.com/breadchris/share/xctf/models'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/xctf/models"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/xctf/models/models"] = map[string]reflect.Value{
		// type definitions
		"Challenge":          reflect.ValueOf((*models.Challenge)(nil)),
		"Comment":            reflect.ValueOf((*models.Comment)(nil)),
		"Competition":        reflect.ValueOf((*models.Competition)(nil)),
		"Evidence":           reflect.ValueOf((*models.Evidence)(nil)),
		"EvidenceConnection": reflect.ValueOf((*models.EvidenceConnection)(nil)),
		"EvidenceReport":     reflect.ValueOf((*models.EvidenceReport)(nil)),
		"HighlightArea":      reflect.ValueOf((*models.HighlightArea)(nil)),
		"HomePage":           reflect.ValueOf((*models.HomePage)(nil)),
		"Page":               reflect.ValueOf((*models.Page)(nil)),
		"User":               reflect.ValueOf((*models.User)(nil)),
		"Writeup":            reflect.ValueOf((*models.Writeup)(nil)),
	}
}
