// Code generated by 'yaegi extract github.com/breadchris/share/deps'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/share/deps"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/share/deps/deps"] = map[string]reflect.Value{
		// type definitions
		"Deps": reflect.ValueOf((*deps.Deps)(nil)),
	}
}
