// Code generated by 'yaegi extract github.com/breadchris/flow/deps'. DO NOT EDIT.

package symbol

import (
	"github.com/breadchris/flow/deps"
	"reflect"
)

func init() {
	Symbols["github.com/breadchris/flow/deps/deps"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewDepsFactory": reflect.ValueOf(deps.NewDepsFactory),

		// type definitions
		"Deps":        reflect.ValueOf((*deps.Deps)(nil)),
		"DepsFactory": reflect.ValueOf((*deps.DepsFactory)(nil)),
	}
}
