// Code generated by 'yaegi extract golang.org/x/net/http/httpproxy'. DO NOT EDIT.

package symbol

import (
	"golang.org/x/net/http/httpproxy"
	"reflect"
)

func init() {
	Symbols["golang.org/x/net/http/httpproxy/httpproxy"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"FromEnvironment": reflect.ValueOf(httpproxy.FromEnvironment),

		// type definitions
		"Config": reflect.ValueOf((*httpproxy.Config)(nil)),
	}
}
