// Code generated by 'yaegi extract golang.org/x/oauth2/clientcredentials'. DO NOT EDIT.

package symbol

import (
	"golang.org/x/oauth2/clientcredentials"
	"reflect"
)

func init() {
	Symbols["golang.org/x/oauth2/clientcredentials/clientcredentials"] = map[string]reflect.Value{
		// type definitions
		"Config": reflect.ValueOf((*clientcredentials.Config)(nil)),
	}
}
