// Code generated by 'yaegi extract google.golang.org/protobuf/types/known/timestamppb'. DO NOT EDIT.

package symbol

import (
	"google.golang.org/protobuf/types/known/timestamppb"
	"reflect"
)

func init() {
	Symbols["google.golang.org/protobuf/types/known/timestamppb/timestamppb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"File_google_protobuf_timestamp_proto": reflect.ValueOf(&timestamppb.File_google_protobuf_timestamp_proto).Elem(),
		"New":                                  reflect.ValueOf(timestamppb.New),
		"Now":                                  reflect.ValueOf(timestamppb.Now),

		// type definitions
		"Timestamp": reflect.ValueOf((*timestamppb.Timestamp)(nil)),
	}
}
