// Code generated by 'yaegi extract google.golang.org/protobuf/types/known/emptypb'. DO NOT EDIT.

package symbol

import (
	"google.golang.org/protobuf/types/known/emptypb"
	"reflect"
)

func init() {
	Symbols["google.golang.org/protobuf/types/known/emptypb/emptypb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"File_google_protobuf_empty_proto": reflect.ValueOf(&emptypb.File_google_protobuf_empty_proto).Elem(),

		// type definitions
		"Empty": reflect.ValueOf((*emptypb.Empty)(nil)),
	}
}
