// Code generated by 'yaegi extract gorm.io/datatypes'. DO NOT EDIT.

package symbol

import (
	"gorm.io/datatypes"
	"reflect"
)

func init() {
	Symbols["gorm.io/datatypes/datatypes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BinUUIDFromString": reflect.ValueOf(datatypes.BinUUIDFromString),
		"Column":            reflect.ValueOf(datatypes.Column),
		"JSONArrayQuery":    reflect.ValueOf(datatypes.JSONArrayQuery),
		"JSONOverlaps":      reflect.ValueOf(datatypes.JSONOverlaps),
		"JSONQuery":         reflect.ValueOf(datatypes.JSONQuery),
		"JSONSet":           reflect.ValueOf(datatypes.JSONSet),
		"NewBinUUIDv1":      reflect.ValueOf(datatypes.NewBinUUIDv1),
		"NewBinUUIDv4":      reflect.ValueOf(datatypes.NewBinUUIDv4),
		"NewNilBinUUID":     reflect.ValueOf(datatypes.NewNilBinUUID),
		"NewTime":           reflect.ValueOf(datatypes.NewTime),
		"NewUUIDv1":         reflect.ValueOf(datatypes.NewUUIDv1),
		"NewUUIDv4":         reflect.ValueOf(datatypes.NewUUIDv4),

		// type definitions
		"BinUUID":                reflect.ValueOf((*datatypes.BinUUID)(nil)),
		"Date":                   reflect.ValueOf((*datatypes.Date)(nil)),
		"JSON":                   reflect.ValueOf((*datatypes.JSON)(nil)),
		"JSONArrayExpression":    reflect.ValueOf((*datatypes.JSONArrayExpression)(nil)),
		"JSONMap":                reflect.ValueOf((*datatypes.JSONMap)(nil)),
		"JSONOverlapsExpression": reflect.ValueOf((*datatypes.JSONOverlapsExpression)(nil)),
		"JSONQueryExpression":    reflect.ValueOf((*datatypes.JSONQueryExpression)(nil)),
		"JSONSetExpression":      reflect.ValueOf((*datatypes.JSONSetExpression)(nil)),
		"NullBool":               reflect.ValueOf((*datatypes.NullBool)(nil)),
		"NullByte":               reflect.ValueOf((*datatypes.NullByte)(nil)),
		"NullFloat64":            reflect.ValueOf((*datatypes.NullFloat64)(nil)),
		"NullInt16":              reflect.ValueOf((*datatypes.NullInt16)(nil)),
		"NullInt32":              reflect.ValueOf((*datatypes.NullInt32)(nil)),
		"NullInt64":              reflect.ValueOf((*datatypes.NullInt64)(nil)),
		"NullString":             reflect.ValueOf((*datatypes.NullString)(nil)),
		"NullTime":               reflect.ValueOf((*datatypes.NullTime)(nil)),
		"Time":                   reflect.ValueOf((*datatypes.Time)(nil)),
		"URL":                    reflect.ValueOf((*datatypes.URL)(nil)),
		"UUID":                   reflect.ValueOf((*datatypes.UUID)(nil)),
	}
}
